### ISSUE TITLE
IRequester example

### ISSUE THREAD

**Issue by GuerrillaCoder** [AngleSharp/AngleSharp.Io#16]
Is there any code samples of using custom IRequester?

I am trying to create multithreaded process where each thread will use a different proxy.  I saw another issue that said this can be done with IRequester but I am not exactly sure how to implement it.

I can see it is a parameter of:

    Configuration.Default.WithRequesters();

But I cannot see how I am supposed to initialize it with proxy information.

Thank you.

**Comment by GuerrillaCoder** [comment]
Seems it takes `HttpClientHandler httpClientHandler = new HttpClientHandler()` as param, i'll experiement with that

**Comment by FlorianRappl** [comment]
I think you are following the right track. Let me know if you need more assistance!

**Comment by GuerrillaCoder** [comment]
Hi Florian,

I got it fetching page but HttpClientHandler doesn't have a timeout property.  Is there anyway I can set a timeout?

Thanks
