### ISSUE TITLE
HttpClientRequester does not use HttpClientHandler.AllowAutoRedirect

### ISSUE THREAD

**Issue by RudeySH** [AngleSharp/AngleSharp.Io#17]
When using `HttpClient`, we can disable automatic redirects by using this:

```
var handler = new HttpClientHandler { AllowAutoRedirect = false };
var client = new HttpClient(handler);
```

However, when using `HttpClientRequester`, the request will still be redirected.

```
var requester = new HttpClientRequester(client);
var configuration = Configuration.Default.WithDefaultLoader(requesters: new[] { requester });
var context = BrowsingContext.New(configuration);
var document = await context.OpenAsync("url that will be redirected");
Console.WriteLine(document.Url); // this is a different url which proves that a redirect happened
```

**Comment by FlorianRappl** [comment]
AngleSharp follows all routes and does that for you. This behavior is not specific for the `HttpClient`, but will be done for any `HttpRequester`.

You could implement your own loader to circumvent this. What is your use-case?

**Comment by RudeySH** [comment]
My use case is browsing a site that will redirect to it's home page when a specific page cannot be found. I don't need to browse the home page when a redirect happens. I got it to work to my liking by doing this:

```
var response = await requester.RequestAsync(request, token);
// use response.StatusCode to decide what to do if a redirect happened
var document = await context.OpenAsync(response);
```

**Comment by sgf** [comment]
> You could implement your own loader to circumvent this. What is your use-case?

When we crawl, we need precise control over our target URL. For example, we need to determine if the URL after a server redirect is the URL we want; if not, the client should be able to choose not to perform the redirect. 

We are not browsers, but crawlers.
We should be free to control everything.

**Comment by FlorianRappl** [comment]
> We should be free to control everything.

And you can control everything. Having a hard time understanding your comment as AngleSharp literally gives you all the options you desire. Don't want AngleSharp to do anything with HTTP? Throw out the handlers and provide streams directly. Don't want to follow up redirects when using HTTP? Implement your own loader.

**Comment by sgf** [comment]
> And you can control everything. Having a hard time understanding your comment as AngleSharp literally gives you all the options you desire. Don't want AngleSharp to do anything with HTTP? Throw out the handlers and provide streams directly. Don't want to follow up redirects when using HTTP? Implement your own loader.


However, it's still not flexible enough. In fact, if we want a system similar to memory, capable of remembering the behavior of certain websites and URLs, then we need to distinguish which URLs require automatic redirection and which do not require redirection and abandonment of access. This means that for the same site, within the same context, different strategies need to be applied when accessing different URL prefixes.

**Comment by FlorianRappl** [comment]
That flexibility should come from you. As mentioned, AngleSharp allows you to do that (everything you just wrote can be covered with a custom loader).

I think what you want is somebody doing that work for you - for free. That is not what is provided here. You have custom requirements - you fulfill them. Sorry to disappoint.

**Comment by sgf** [comment]
> I think what you want is somebody doing that work for you - for free. That is not what is provided here. You have custom requirements - you fulfill them. Sorry to disappoint.


I didn't ask you to do that; I was just casually mentioning the use case for this issue based on your question.

> You could implement your own loader to circumvent this. What is your use-case?
