### ISSUE TITLE
Missing AngleSharp.Io.Network namespace in 0.16.0 nuget package

### ISSUE THREAD

**Issue by bluelunar** [AngleSharp/AngleSharp.Io#31]
It's available in 0.15.0, but it seems to be missing in 0.16.0

**Comment by FlorianRappl** [comment]
Hm sure you installed `AngleSharp` in 0.16.0 and `AngleSharp.Io` in 0.16.0?

**Comment by bluelunar** [comment]
Weird, I was able to find it after testing with a blank project.
