### ISSUE TITLE
Creating a form resulting infinite document awaiting from https page

### ISSUE THREAD

**Issue by TuTAH1** [AngleSharp/AngleSharp.Io#32]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
I haven't found the FAQ
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

That's super strange bug I found. The code
```cs
var requester = new DefaultHttpRequester("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0");
var config = new Configuration().WithDefaultLoader().With(requester);
var document = await BrowsingContext.New(config).OpenAsync(urlAddress);
```
is **not** working if the Form was created **and** urlAddress is https

## Steps to Reproduce

1. Download a project from [here](https://github.com/TuTAH1/AngleSharpTest) **or**:
  - Create .NET 6 Winforms project
  - Get AngleSharp from nuGet
  - Paste [this code](https://github.com/TuTAH1/AngleSharpTest/blob/main/Program.cs)
2. Launch it. Don't see "all ok" message
3. Comment `var form = new Form1();` line and launch again
4. See "all ok" message
5. Uncomment the line, remove "https"//" from link
6. See "all ok" message

**Expected behavior:** [getting either document or exception]

**Actual behavior:** [infinite loop]

**Environment details:** [Windows 10, .NET 6]

**Comment by FlorianRappl** [comment]
Hm bit of a strange thing. You post it here, but you did in fact use the `DefaultHttpRequester`, which is the one from `AngleSharp`. Are you sure you did not intend to use the `HttpClientRequester`?

Regarding the question: Potentially the CA verification fails. I'd recommend disabling HTTPS verification to see if this is the issue.

Related:
https://social.msdn.microsoft.com/Forums/en-US/2d5e64ca-e9af-402e-8852-dc4b70dc3c5f/http-post-request-gt-getresponse-hangs?forum=netfxnetcom
https://stackoverflow.com/questions/48969650/https-request-fails-only-in-net-web-app
https://stackoverflow.com/questions/42746190/https-request-fails-using-httpclient

**Comment by TuTAH1** [comment]
> You post it here, but you did in fact use the `DefaultHttpRequester`, which is the one from `AngleSharp`. Are you sure you did not intend to use the `HttpClientRequester`?

What is HttpClientRequester? I don't see this class in AngleSharp.

> Regarding the question: Potentially the CA verification fails. I'd recommend disabling HTTPS verification to see if this is the issue.

It may be true (haven't checked yet), but why removing Form creating solves this problem (with absolute repeatability)?

**Comment by FlorianRappl** [comment]
> What is HttpClientRequester? I don't see this class in AngleSharp. DefaultHttpRequester is from AngleSharp.Io.

You confuse a namespace with a library. The `AngleSharp.Io` namespace is already in `AngleSharp`, but this is the `AngleSharp.Io` library, which brings more requesters such as

https://github.com/AngleSharp/AngleSharp.Io/blob/devel/src/AngleSharp.Io/Network/HttpClientRequester.cs

> It may be true (haven't checked yet), but why removing Form creating solves this problem (with absolute repeatability)?

Not sure what you refer to. You may run into a deadlock here, but again - from the description you focus on an HTTPS problem. Maybe first check there.

**Comment by TuTAH1** [comment]
> Not sure what you refer to.

Exactly what I wroted: see steps 1-4 you can reproduce.

I added 
```
ServicePointManager.SecurityProtocol |=
	SecurityProtocolType.Tls12 | 
	SecurityProtocolType.Tls11 | 
	SecurityProtocolType.Tls;
```
to the start of my code, but it didn't solve my problem. I also tried use `HttpClientRequester` and have exactly same behavior.
```
var client = new HttpClient();
client.DefaultRequestHeaders.Add("Accept-Language", "en-US,en;q=0.812");
var requester = new HttpClientRequester(client);
var config = Configuration.Default.WithRequester(requester).WithDefaultLoader();
var context = BrowsingContext.New(config);
var document = await context.OpenAsync(urlAddress);
```

**Comment by FlorianRappl** [comment]
![image](https://user-images.githubusercontent.com/1766191/190573062-ac1ce487-23da-45b1-a6fb-0f5e6f2e14f2.png)

The thing runs. As written you may run into a deadlock - I'd suggest to `ConfigureAwait(false)` or similar. In any case this does not seem like a problem with the requester or AngleSharp itself.

**Comment by TuTAH1** [comment]
> ![image](https://user-images.githubusercontent.com/1766191/190573062-ac1ce487-23da-45b1-a6fb-0f5e6f2e14f2.png)
> 
> The thing runs. As written you may run into a deadlock - I'd suggest to `ConfigureAwait(false)` or similar. In any case this does not seem like a problem with the requester or AngleSharp itself.

This thing runs. Until you execute Form initialisation as I wroted in reproduction steps
