### ISSUE TITLE
TypeLoadException when using AngleSharp.Io with AngleSharp 0.9.4

### ISSUE THREAD

**Issue by YehudahA** [AngleSharp/AngleSharp.Io#7]
1. I created new VS project
2. I installed AngleSharp 0.9.4 package, and AngleSharp.IO 0.1 package.
3. I tried to run this code:

``` cs
            var requesters = new IRequester[] { };
            var service = new LoaderService(requesters);
```
TypeLoadException  thrown.

**Comment by FlorianRappl** [comment]
Two things:

1. This is an issue of AngleSharp.Io.
2. You should be able to see that AngleSharp.Io is made for v0.9.3 - most of the times higher versions can be used, but this not the case for v0.9.4 as some names (e.g., `MimeTypes` to `MimeTypeNames`) have been changed.

Has nothing to do with AngleSharp.

**Comment by YehudahA** [comment]
@FlorianRappl, we are in AngleSharp.Io repo, not AngleSharp.

**Comment by FlorianRappl** [comment]
My bad! Changed accordingly. Don't know why I was confused at first place, but that makes it an enhancement.

**Comment by YehudahA** [comment]
You was confused because the original title was "AngleSharp 0.9.4".

**Comment by FlorianRappl** [comment]
Yes, I think so. Thanks for bearing with me!

**Comment by YehudahA** [comment]
you're fast. :v:
