### ISSUE TITLE
Portable AngleSharp.Io?

### ISSUE THREAD

**Issue by joelverhagen** [AngleSharp/AngleSharp.Io#9]
Right now, it looks like the `AngleSharp.Io` package targets `net45`. Are there any plans to make this package (or a subset of functionality available on other TFMs?

In particular, I was wondering if the new [.NET Platform standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) will be supported. The piece that I worked on before (an adapter for `HttpClient`) should work on `netstandard1.1`, since this is the earliest version that supports `HttpClient`.

**Comment by FlorianRappl** [comment]
I don't know yet. Anglesharp.Io is supposed to be platform-dependent, as it will have file system integrations. But that does not exclude the .NET platform. A decision can only be done in a later stage. In the end the supported platforms are determined naturally (i.e., implicitly), by seeing what kind of libraries (from the "framework") are required / exposed as dependencies.

**Comment by FlorianRappl** [comment]
See #12 for the answer to this issue. Yes, indeed `netstandard1.1` is the one to go for. Thanks @joelverhagen for proposing this!
